
## Tarefa: **S01L05a - 08/05 a 14/05**
Autor: José Luiz Neves Voltan

UTFPR


### Descrição da Tarefa:

Tomando como base arquivo L05_manual-pipeline.ipynb montem um pipeline de pré-processamento de dados para realizar a classificação da base de dados "breast_cancer"

- Essa base de dados "breast cancer" está disponível na própria biblioteca do scikit. Também é fácil achar essa base na internet, em outros formatos (txt, csv, etc), se seja da preferência

Esse pipeline deve conter

3.1 - abertura do dados

3.2 - pré-processamento para limpeza dos dados (se precisar)(conversão de características, conversão de rótulos/classes, imputação de valores faltantes, etc)

3.3 - divisão em treinamento e teste

3.4 - normalização dos dados

3.5 - classificação com knn

3.6 - avaliação de acurácia

4 - a solução deve usar as bibliotecas pandas, numpy e scikit-learn

5 - Para cada exercício/comando, fazer um pequeno comentário em texto do que o comando realiza, utilizando linguagem markdown (ambiente colab)

6 - Compartilhar o link (no colab, botão superior direito, compartilhar, gerar link, e colocar o link aqui no moodle para minha verificação)

- não esquecer de dar acesso de leitura para os que tiverem o link



### Importando as bibliotecas

In [17]:
#Importando as bibliotecas:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

from sklearn.datasets import load_breast_cancer  # Irei utilizar o dataset a partir da própria biblioteca

from collections import Counter

### Obtenção do dataset

- Para maiores informações do dataset vide:  `https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html`

- Nome das colunas do Dataset

In [11]:
load_breast_cancer().feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

- Rótulos

In [12]:
load_breast_cancer().target_names

array(['malignant', 'benign'], dtype='<U9')

In [4]:
# Importando...
 X, y = load_breast_cancer(return_X_y=True)  
 # Perceba que o parâmetro passado ja faz a divisão de características e Label

In [7]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [8]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

- Nesse momento já temos nosso dataset dividido entre características e labels.

### Separando em conjunto de teste e treinamento

*   Iremos utilizar o método train_test_split()  para maiores detalhes leia: `https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html`

* Perceba que parâmetro shuffle=True não era necessário por ser o *default*


In [13]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.2,shuffle=True, stratify=y)

- Vamos verificar a quantidade de ocorrências das labels e se a proporção foi mantida como esperado (pois usamos `stratify=y`)

In [21]:
# Antes
print(Counter(y))
total=357+212
proporcao_1= 357/total
print(proporcao_1)

Counter({1: 357, 0: 212})
0.6274165202108963


In [24]:
#Depois,  no conjunto de treinamento

#np.bincount(y_treinamento)  é só outra forma de encontrar essa proporção
print(Counter(y_treinamento))

#Verificando a proporção
total=170+285
proporcao_1= 285/total
print(proporcao_1)

Counter({1: 285, 0: 170})
0.6263736263736264


### Normalizando

- Para entender como a Classe **StandardScaler** funciona vide: `https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html `

- A normalização utiliza a fórmula z = (x - u) / s

"*where u is the mean of the training samples or zero if with_mean=False, and s is the standard deviation of the training samples or one if with_std=False.*"

In [25]:
scaler = StandardScaler()
scaler.fit(X_treinamento)
X_treinamento_std = scaler.transform(X_treinamento)
X_teste_std = scaler.transform(X_teste)
X_treinamento_std

array([[-0.40213226, -0.56775283, -0.40101947, ..., -0.54396123,
         0.23526552,  0.07740845],
       [ 0.56603796, -0.99108596,  0.50245169, ..., -0.05282031,
        -0.2285337 , -0.76328187],
       [-0.60776133, -0.28476384, -0.66720968, ..., -1.33841382,
        -1.18937372, -0.74967847],
       ...,
       [-0.73056759, -0.18583273, -0.75884214, ..., -0.50718242,
         0.45529313, -0.30022203],
       [ 0.23760264,  0.67693859,  0.22174955, ...,  0.21810179,
         0.3808953 ,  0.45503892],
       [ 0.08909275,  1.33954697,  0.15043379, ...,  0.06220807,
         0.41888568,  0.98774819]])

- Verificando a média e desvio padrão


In [27]:
print(scaler.mean_)
print(scaler.var_)

[1.41580462e+01 1.91677143e+01 9.21818242e+01 6.57019560e+02
 9.65065495e-02 1.04971890e-01 9.00926916e-02 4.96541363e-02
 1.81988571e-01 6.28229890e-02 4.00640879e-01 1.20146857e+00
 2.83449297e+00 3.98344637e+01 7.02398022e-03 2.53658220e-02
 3.20595815e-02 1.18480835e-02 2.05368066e-02 3.77370769e-03
 1.63003604e+01 2.55903736e+01 1.07438835e+02 8.81944615e+02
 1.32653714e-01 2.55618352e-01 2.75681626e-01 1.16389873e-01
 2.92237363e-01 8.41474066e-02]
[1.22601548e+01 1.88917042e+01 5.81682337e+02 1.24165307e+05
 1.95439514e-04 2.81313578e-03 6.36365283e-03 1.49409565e-03
 7.21442551e-04 5.19020289e-05 7.62802658e-02 2.95955299e-01
 4.01394719e+00 2.13252414e+03 8.88111993e-06 3.16543552e-04
 9.87874858e-04 3.77400265e-05 6.56159455e-05 7.55825696e-06
 2.30027268e+01 3.86825952e+01 1.10725624e+03 3.19449013e+05
 5.36118225e-04 2.49640189e-02 4.41959341e-02 4.36533095e-03
 3.99094014e-03 3.37741846e-04]


### Criando e aplicando o modelo
- Iremos utilizar o KNN usando a quantidade de vizinhos como 3
- Inicialmente irmeos treinar o modelo usando o conjunto de treinamento, já normalizado.

In [28]:
knn_model = KNeighborsClassifier(n_neighbors=3)
knn_model.fit(X_treinamento_std, y_treinamento)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

- Agora iremos prever os rótulos com base no modelo criado e treinado

In [30]:
y_pred = knn_model.predict(X_teste_std)
print(y_pred)
print(y_teste)

[0 1 1 1 0 0 1 1 1 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 0 0 1 1 1 1 1 0 0 0 1 0
 0 0 1 1 0 0 0 1 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 1 1 1 1
 0 1 1 1 0 1 1 0 1 0 0 0 1 1 1 1 0 1 0 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0
 1 0 1]
[0 1 1 1 0 0 1 1 1 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 0 0 1 1 1 1 1 0 0 0 1 0
 0 0 1 1 0 0 0 1 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 1 1
 0 1 1 1 0 1 1 0 1 0 0 0 1 1 1 1 0 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0
 1 0 1]


### Métricas de acerto

* Podemos melhorarmos a visualização anterior usando um dataframe para uma melhor comparação

In [37]:
dataset = pd.DataFrame({'Previsto': y_pred, 'Teste': y_teste})
def compara(x): 
  if x[0]==x[1]: return 1
  else: return 0

dataset['Acertou']= dataset.apply(compara, axis=1)

In [38]:
dataset

Previsto  Teste  Acertou
0           0      0        1
1           1      1        1
2           1      1        1
3           1      1        1
4           0      0        1
..        ...    ...      ...
109         1      1        1
110         0      0        1
111         1      1        1
112         0      0        1
113         1      1        1

[114 rows x 3 columns]

In [39]:
Counter(dataset['Acertou'])

Counter({0: 2, 1: 112})

In [40]:
accuracy_score(y_teste, y_pred)

0.9824561403508771